#!/bin/sh

SRCFILE=$1

if [ x${SRCFILE} = x ]; then
    echo "Usage: $0 SRCFILE.flac" 1>&2
    exit 1
fi

if [ ! -r ${SRCFILE} ]; then
    echo "Cannot read $SRCFILE" 1>&2
    exit 1
fi
    
for dir in flac mono stereo; do
    if [ ! -d ${dir} ]; then
        echo "Missing directory: ${dir}" 1>&2
        exit 1
    fi
done

for format in mono stereo; do
    for dir in 16000 32000 48000 8000; do
        if [ ! -d ${format}/${dir} ]; then
            echo "Missing directory: ${format}/${dir}" 1>&2
            exit 1
        fi
    done
done

BASENAME=`openssl md5 -r ${SRCFILE} | sed -e 's,^\(......\).*,\1,'`

if [ -e flac/${BASENAME}.flac ]; then
    echo "File ${BASENAME} already exists" 1>&2
    exit 1
fi
    
   
cp ${SRCFILE} flac/${BASENAME}.flac

TMPSTEREO=/tmp/$$_trimmed.wav
sox ${SRCFILE} ${TMPSTEREO} silence 1 1 0.01% reverse silence 1 1 0.01% reverse
if [ $? -ne 0 ]; then
    echo "Error executing sox" 1>&2
    rm -f ${TMPSTEREO}
    exit 1
fi

TMPMONO=/tmp/$$_mono.wav
sox ${TMPSTEREO} ${TMPMONO} channels 1
if [ $? -ne 0 ]; then
    echo "Error executing sox" 1>&2
    rm -f ${TMPSTEREO} ${TMPMONO}
    exit 1
fi

for rate in 16000 32000 48000 8000; do
    sox ${TMPSTEREO} -b 16 stereo/${rate}/${BASENAME}.wav rate ${rate}
    if [ $? -ne 0 ]; then
        echo "Error executing sox" 1>&2
        rm -f ${TMPSTEREO} ${TMPMONO} 
        exit 1
    fi
    sox ${TMPMONO} -b 16 mono/${rate}/${BASENAME}.wav rate ${rate}
    if [ $? -ne 0 ]; then
        echo "Error executing sox" 1>&2
        rm -f ${TMPSTEREO} ${TMPMONO} 
        exit 1
    fi
done

rm -f ${TMPSTEREO} ${TMPMONO}

echo Added ${BASENAME}



